:setvar path "C:\repos\git_repos\izzy-lazerson\DB_Scripts"
:r $(path)\Step_01_Create_DB.sql
:r $(path)\Step_02_Cleanup_DB.sql
:r $(path)\Step_03_TABLE_Parties.sql
:r $(path)\Step_04_TABLE_Party_Types.sql
:r $(path)\Step_05_TABLE_Party_Phone.sql
:r $(path)\Step_06_TABLE_Phone_Types.sql
:r $(path)\Step_07_TABLE_Tax_Types.sql
:r $(path)\Step_08_TABLE_Individuals.sql
:r $(path)\Step_09_TABLE_Companies.sql
:r $(path)\Step_10_TABLE_Agencies.sql
:r $(path)\Step_11_TABLE_Company_Owners.sql
:r $(path)\Step_12_TABLE_Agency_Managers.sql
:r $(path)\Step_13_TABLE_Tax_Payments.sql
:r $(path)\Step_14_Setup_FK_Relationships.sql
:r $(path)\Step_15_PROC_usp_Create_Party.sql
:r $(path)\Step_16_PROC_usp_Add_Party_Phone.sql
:r $(path)\Step_17_PROC_usp_Create_Individual.sql
:r $(path)\Step_18_PROC_usp_Add_Agency_Manager.sql
:r $(path)\Step_19_PROC_usp_Add_Company_Owner.sql
:r $(path)\Step_20_FUNC_ufn_Split.sql
:r $(path)\Step_21_PROC_usp_Create_Agency.sql
:r $(path)\Step_22_PROC_usp_Create_Company.sql
:r $(path)\Step_23_PROC_usp_Create_Tax_Payment.sql
:r $(path)\Step_24_VIEW_v_Agencies.sql
:r $(path)\Step_25_VIEW_v_Taxpayers.sql
:r $(path)\Step_26_VIEW_v_Taxpayer_Payments.sql
:r $(path)\Step_27_FUNC_ufn_Get_Payer_Payments_By_Month.sql
:r $(path)\Step_28_VIEW_v_Company_Owner_Payments.sql
:r $(path)\Step_29_FUNC_ufn_Get_Owner_Total_Payments.sql
:r $(path)\Step_30_INSERT_Sample_Data.sql